<?php
echo "...Đang xóa dữ liệu trong bảng...<br><br>";
$db->query("TRUNCATE TABLE media_file");
echo "- Xóa thành công media_file<br>";
$db->query("TRUNCATE TABLE media_relationship");
echo "- Xóa thành công media_relationship<br>";
$db->query("TRUNCATE TABLE post");
echo "- Xóa thành công post<br>";
$db->query("TRUNCATE TABLE postcat");
echo "- Xóa thành công postcat<br>";
$db->query("TRUNCATE TABLE postcat_lang");
echo "- Xóa thành công postcat_lang<br>";
$db->query("TRUNCATE TABLE post_album");
echo "- Xóa thành công post_album<br>";
$db->query("TRUNCATE TABLE post_album_menu");
echo "- Xóa thành công post_album_menu<br>";
$db->query("TRUNCATE TABLE post_lang");
echo "- Xóa thành công post_lang<br>";
$db->query("TRUNCATE TABLE post_meta");
echo "- Xóa thành công post_meta<br>";
$db->query("TRUNCATE TABLE post_meta_key");
echo "- Xóa thành công post_meta_key<br>";
$db->query("TRUNCATE TABLE tag");
echo "- Xóa thành công tag<br>";
$db->query("TRUNCATE TABLE tag_relationship");
echo "- Xóa thành công tag_relationship<br>";
$db->query("TRUNCATE TABLE vn_contacts");
echo "- Xóa thành công vn_contacts<br>";
$db->query("TRUNCATE TABLE vn_gallery_menu");
echo "- Xóa thành công vn_gallery_menu<br>";
$db->query("TRUNCATE TABLE vn_gallery_menu_lang");
echo "- Xóa thành công vn_gallery_menu_lang<br>";
$db->query("TRUNCATE TABLE vn_import");
echo "- Xóa thành công vn_import<br>";
$db->query("TRUNCATE TABLE vn_menu");
echo "- Xóa thành công vn_menu<br>";
$db->query("TRUNCATE TABLE vn_modules");
echo "- Xóa thành công vn_modules<br>";
$db->query("TRUNCATE TABLE vn_online");
echo "- Xóa thành công vn_online<br>";
$db->query("TRUNCATE TABLE vn_online_daily");
echo "- Xóa thành công vn_online_daily<br>";
$db->query("TRUNCATE TABLE vn_page");
echo "- Xóa thành công vn_page<br>";
$db->query("TRUNCATE TABLE vn_page_lang");
echo "- Xóa thành công vn_page_lang<br>";
$db->query("TRUNCATE TABLE vn_support");
echo "- Xóa thành công vn_support<br>";
$db->query("TRUNCATE TABLE vn_user_permission");
echo "- Xóa thành công vn_user_permission<br>";
echo "............................................................<br>";
echo "....................Hoàn thành....................<br>";
echo "............................................................<br>";
echo "<br>";
echo "Kiểm tra dữ liệu bảng vn_user_group"
?>